;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Dialogue.Intro.1",NewTagName="Dialogue.Intro.Intro1")
+GameplayTagRedirects=(OldTagName="Dialogue.Couloir.Couloir 45",NewTagName="Dialogue.Couloir.Couloir 5")
+GameplayTagRedirects=(OldTagName="Dialogue.Couloir.Couloir 56",NewTagName="Dialogue.Couloir.Couloir 6")
+GameplayTagList=(Tag="Dialogue",DevComment="")
+GameplayTagList=(Tag="Dialogue.Couloir",DevComment="")
+GameplayTagList=(Tag="Dialogue.Couloir.COeur",DevComment="")
+GameplayTagList=(Tag="Dialogue.Couloir.Couloir1",DevComment="")
+GameplayTagList=(Tag="Dialogue.Couloir.Couloir 2",DevComment="")
+GameplayTagList=(Tag="Dialogue.Couloir.Couloir 3",DevComment="")
+GameplayTagList=(Tag="Dialogue.Couloir.Couloir 4",DevComment="")
+GameplayTagList=(Tag="Dialogue.Couloir.Couloir 5",DevComment="")
+GameplayTagList=(Tag="Dialogue.Couloir.Couloir 6",DevComment="")
+GameplayTagList=(Tag="Dialogue.Couloir.Couloir 7",DevComment="")
+GameplayTagList=(Tag="Dialogue.Couloir.Couloir 8",DevComment="")
+GameplayTagList=(Tag="Dialogue.Couloir.Couloir 9",DevComment="")
+GameplayTagList=(Tag="Dialogue.Intro",DevComment="")
+GameplayTagList=(Tag="Dialogue.Intro.Intro1",DevComment="")
+GameplayTagList=(Tag="Dialogue.Intro.Intro2",DevComment="")
+GameplayTagList=(Tag="Dialogue.Intro.Intro3",DevComment="")
+GameplayTagList=(Tag="Dialogue.Intro.Intro4",DevComment="")
+GameplayTagList=(Tag="Dialogue.Intro.Intro5",DevComment="")
+GameplayTagList=(Tag="Dialogue.Intro.Intro6",DevComment="")
+GameplayTagList=(Tag="Dialogue.Test",DevComment="")

